/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface KuklychAmbulanceWlApp {
        "ambulanceId": string;
        "apiBase": string;
        /**
          * @default ""
         */
        "basePath": string;
    }
    interface KuklychAmbulanceWlEditor {
        "ambulanceId": string;
        "apiBase": string;
        "entryId": string;
    }
    interface KuklychAmbulanceWlList {
        "ambulanceId": string;
        "apiBase": string;
    }
}
export interface KuklychAmbulanceWlEditorCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLKuklychAmbulanceWlEditorElement;
}
export interface KuklychAmbulanceWlListCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLKuklychAmbulanceWlListElement;
}
declare global {
    interface HTMLKuklychAmbulanceWlAppElement extends Components.KuklychAmbulanceWlApp, HTMLStencilElement {
    }
    var HTMLKuklychAmbulanceWlAppElement: {
        prototype: HTMLKuklychAmbulanceWlAppElement;
        new (): HTMLKuklychAmbulanceWlAppElement;
    };
    interface HTMLKuklychAmbulanceWlEditorElementEventMap {
        "editor-closed": string;
    }
    interface HTMLKuklychAmbulanceWlEditorElement extends Components.KuklychAmbulanceWlEditor, HTMLStencilElement {
        addEventListener<K extends keyof HTMLKuklychAmbulanceWlEditorElementEventMap>(type: K, listener: (this: HTMLKuklychAmbulanceWlEditorElement, ev: KuklychAmbulanceWlEditorCustomEvent<HTMLKuklychAmbulanceWlEditorElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLKuklychAmbulanceWlEditorElementEventMap>(type: K, listener: (this: HTMLKuklychAmbulanceWlEditorElement, ev: KuklychAmbulanceWlEditorCustomEvent<HTMLKuklychAmbulanceWlEditorElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLKuklychAmbulanceWlEditorElement: {
        prototype: HTMLKuklychAmbulanceWlEditorElement;
        new (): HTMLKuklychAmbulanceWlEditorElement;
    };
    interface HTMLKuklychAmbulanceWlListElementEventMap {
        "entry-clicked": string;
    }
    interface HTMLKuklychAmbulanceWlListElement extends Components.KuklychAmbulanceWlList, HTMLStencilElement {
        addEventListener<K extends keyof HTMLKuklychAmbulanceWlListElementEventMap>(type: K, listener: (this: HTMLKuklychAmbulanceWlListElement, ev: KuklychAmbulanceWlListCustomEvent<HTMLKuklychAmbulanceWlListElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLKuklychAmbulanceWlListElementEventMap>(type: K, listener: (this: HTMLKuklychAmbulanceWlListElement, ev: KuklychAmbulanceWlListCustomEvent<HTMLKuklychAmbulanceWlListElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLKuklychAmbulanceWlListElement: {
        prototype: HTMLKuklychAmbulanceWlListElement;
        new (): HTMLKuklychAmbulanceWlListElement;
    };
    interface HTMLElementTagNameMap {
        "kuklych-ambulance-wl-app": HTMLKuklychAmbulanceWlAppElement;
        "kuklych-ambulance-wl-editor": HTMLKuklychAmbulanceWlEditorElement;
        "kuklych-ambulance-wl-list": HTMLKuklychAmbulanceWlListElement;
    }
}
declare namespace LocalJSX {
    interface KuklychAmbulanceWlApp {
        "ambulanceId"?: string;
        "apiBase"?: string;
        /**
          * @default ""
         */
        "basePath"?: string;
    }
    interface KuklychAmbulanceWlEditor {
        "ambulanceId"?: string;
        "apiBase"?: string;
        "entryId"?: string;
        "onEditor-closed"?: (event: KuklychAmbulanceWlEditorCustomEvent<string>) => void;
    }
    interface KuklychAmbulanceWlList {
        "ambulanceId"?: string;
        "apiBase"?: string;
        "onEntry-clicked"?: (event: KuklychAmbulanceWlListCustomEvent<string>) => void;
    }

    interface KuklychAmbulanceWlAppAttributes {
        "basePath": string;
        "apiBase": string;
        "ambulanceId": string;
    }
    interface KuklychAmbulanceWlEditorAttributes {
        "entryId": string;
        "ambulanceId": string;
        "apiBase": string;
    }
    interface KuklychAmbulanceWlListAttributes {
        "apiBase": string;
        "ambulanceId": string;
    }

    interface IntrinsicElements {
        "kuklych-ambulance-wl-app": Omit<KuklychAmbulanceWlApp, keyof KuklychAmbulanceWlAppAttributes> & { [K in keyof KuklychAmbulanceWlApp & keyof KuklychAmbulanceWlAppAttributes]?: KuklychAmbulanceWlApp[K] } & { [K in keyof KuklychAmbulanceWlApp & keyof KuklychAmbulanceWlAppAttributes as `attr:${K}`]?: KuklychAmbulanceWlAppAttributes[K] } & { [K in keyof KuklychAmbulanceWlApp & keyof KuklychAmbulanceWlAppAttributes as `prop:${K}`]?: KuklychAmbulanceWlApp[K] };
        "kuklych-ambulance-wl-editor": Omit<KuklychAmbulanceWlEditor, keyof KuklychAmbulanceWlEditorAttributes> & { [K in keyof KuklychAmbulanceWlEditor & keyof KuklychAmbulanceWlEditorAttributes]?: KuklychAmbulanceWlEditor[K] } & { [K in keyof KuklychAmbulanceWlEditor & keyof KuklychAmbulanceWlEditorAttributes as `attr:${K}`]?: KuklychAmbulanceWlEditorAttributes[K] } & { [K in keyof KuklychAmbulanceWlEditor & keyof KuklychAmbulanceWlEditorAttributes as `prop:${K}`]?: KuklychAmbulanceWlEditor[K] };
        "kuklych-ambulance-wl-list": Omit<KuklychAmbulanceWlList, keyof KuklychAmbulanceWlListAttributes> & { [K in keyof KuklychAmbulanceWlList & keyof KuklychAmbulanceWlListAttributes]?: KuklychAmbulanceWlList[K] } & { [K in keyof KuklychAmbulanceWlList & keyof KuklychAmbulanceWlListAttributes as `attr:${K}`]?: KuklychAmbulanceWlListAttributes[K] } & { [K in keyof KuklychAmbulanceWlList & keyof KuklychAmbulanceWlListAttributes as `prop:${K}`]?: KuklychAmbulanceWlList[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "kuklych-ambulance-wl-app": LocalJSX.IntrinsicElements["kuklych-ambulance-wl-app"] & JSXBase.HTMLAttributes<HTMLKuklychAmbulanceWlAppElement>;
            "kuklych-ambulance-wl-editor": LocalJSX.IntrinsicElements["kuklych-ambulance-wl-editor"] & JSXBase.HTMLAttributes<HTMLKuklychAmbulanceWlEditorElement>;
            "kuklych-ambulance-wl-list": LocalJSX.IntrinsicElements["kuklych-ambulance-wl-list"] & JSXBase.HTMLAttributes<HTMLKuklychAmbulanceWlListElement>;
        }
    }
}
